
parameters:
    class_vitrequest: AppBundle\Services\VitRequest
    class_vitmail: AppBundle\Services\VitMail

services:
    vitrequest:
        class:     %class_vitrequest%
        arguments: ["@request_stack"]

    vitmail:
            class:     %class_vitmail%
            arguments: ["@mailer"]

    acme_locale.locale_listener:
            class: AppBundle\EventListener\LocaleListener
            arguments: ["%kernel.default_locale%"]
            tags:
                - { name: kernel.event_subscriber }