
parameters:
    class_vitrequest: AppBundle\Services\VitRequest
    class_vitmail: AppBundle\Services\VitMail

services:
    vitrequest:
        class:     %class_vitrequest%
        arguments: ["@request_stack"]

    vitmail:
            class:     %class_vitmail%
            arguments: ["@mailer"]
